apiVersion: v1
kind: Service
metadata:
  name: angular-service
  namespace: default
spec:
  selector:
    app: angular-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
