- name: build docker image {{ docker_registry }}/{{ docker_image_name }}:{{ app_source_version }}
  docker_image:
    docker_api_version: "{{ docker_api_version }}"
    path: "{{ docker_working_directory }}/{{ app_name }}/{{ app_dockerfile_path }}"
    tag: "{{ app_source_version }}"
    name: "{{ docker_registry }}/{{ docker_image_name }}"
    state: build


- name: push docker image {{ docker_registry }}/{{ docker_image_name }}:{{ app_source_version }} to {{ docker_registry }}
  shell: "docker push {{ docker_registry }}/{{ docker_image_name }}:{{ app_source_version }}"
