apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-myservicea
  namespace: default
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - pacemacker-1.onetech-group.corp
    secretName: your-tls-secret    # Reference to the K8s Secret containing your TLS cert
  rules:
  - host: pacemacker-1.onetech-group.corp
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: angular-service
            port:
              number: 80
